### ISSUE TITLE
pfUI changes only works for melee

### ISSUE THREAD

**Issue by Sprysea** [Lexiebean/Turtle-WoW-Macros#1]
Hi,

It seems the changes in the custom file will only affect targets and melee ones at that.
Setting it on the Playerframe will either show the melee damage, zeroes or the selected/attacked NPC target, but on the player frame.
If Target or Player is Hunter or other caster class, it will not display correctly.

Also doesn't display correctly if target is a player.

**Comment by Lexiebean** [comment]
This is a limitation of the vanilla API.

https://vanilla-wow-archive.fandom.com/wiki/API_UnitDamage
